name: InvSee
version: ${project.version}
main: com.metox.invsee.InvSee
website: https://discord.gg/forges
api-version: 1.13
author: chizzar-dev
description: Baska oyuncularin envanterini zirh ve yan el dahil goruntule. Coslant.

commands:
  invsee:
    description: Baska oyuncunun envanterini veya ender sandigini gor
    usage: /invsee <oyuncu> | /invsee enderchest <oyuncu>
    aliases: [envanter, inv]

permissions:
  invsee.use:
    description: Baskalarinin envanterini gorebilir ve duzenleyebilir
    default: op
